dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - test
  - build and publish
  - deploy
if: tag IS blank

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "10"
      script: yarn test
    - stage: build and publish
      language: node_js
      node_js:
        - "10"
      script: 
        - yarn build
        - touch build/Staticfile
        - tar -zcvf FoodFinder.tar.gz build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "FoodFinder.tar.gz"
        skip_cleanup: true
    - stage: deploy
      install: skip
      script:
        - echo "Downloading FoodFinder $RELEASE_TAG"
        - wget https://github.com/$GITHUB_USERNAME/FoodFinder/releases/download/$RELEASE_TAG/FoodFinder.tar.gz
        - tar -zxvf FoodFinder.tar.gz
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: development 




